ALLFLEXING_HOOK_RUNTIME_SOURCES := \
	$(ALLFLEXING_ROOT)/FLEXCHookEngine.m \
	$(ALLFLEXING_ROOT)/FLEXHooking.m \
	$(ALLFLEXING_ROOT)/FLEXHookRegistry.m \
	$(ALLFLEXING_ROOT)/FLEXRuntimeScanner.m \
	$(ALLFLEXING_ROOT)/FLEXSymbolRebind.m
